//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.8
//
// <auto-generated>
//
// Generated from file `CoffeMach.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package servicios;

public interface BrokerService extends com.zeroc.Ice.Object
{
    void registerServer(ServerRecieveAlarmServicePrx subscriber, com.zeroc.Ice.Current current);

    void unregisterServer(ServerRecieveAlarmServicePrx subscriber, com.zeroc.Ice.Current current);

    void sendAlarm(int codMaquina, String type, String idInsumo, String idSumin, String idIngrediente, int cantidad, Moneda moneda, AlarmaServicePrx alarmaService, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::servicios::BrokerService"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::servicios::BrokerService";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_registerServer(BrokerService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        ServerRecieveAlarmServicePrx iceP_subscriber;
        iceP_subscriber = ServerRecieveAlarmServicePrx.uncheckedCast(istr.readProxy());
        inS.endReadParams();
        obj.registerServer(iceP_subscriber, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_unregisterServer(BrokerService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        ServerRecieveAlarmServicePrx iceP_subscriber;
        iceP_subscriber = ServerRecieveAlarmServicePrx.uncheckedCast(istr.readProxy());
        inS.endReadParams();
        obj.unregisterServer(iceP_subscriber, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendAlarm(BrokerService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_codMaquina;
        String iceP_type;
        String iceP_idInsumo;
        String iceP_idSumin;
        String iceP_idIngrediente;
        int iceP_cantidad;
        Moneda iceP_moneda;
        AlarmaServicePrx iceP_alarmaService;
        iceP_codMaquina = istr.readInt();
        iceP_type = istr.readString();
        iceP_idInsumo = istr.readString();
        iceP_idSumin = istr.readString();
        iceP_idIngrediente = istr.readString();
        iceP_cantidad = istr.readInt();
        iceP_moneda = Moneda.ice_read(istr);
        iceP_alarmaService = AlarmaServicePrx.uncheckedCast(istr.readProxy());
        inS.endReadParams();
        obj.sendAlarm(iceP_codMaquina, iceP_type, iceP_idInsumo, iceP_idSumin, iceP_idIngrediente, iceP_cantidad, iceP_moneda, iceP_alarmaService, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "registerServer",
        "sendAlarm",
        "unregisterServer"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 1:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 2:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 4:
            {
                return _iceD_registerServer(this, in, current);
            }
            case 5:
            {
                return _iceD_sendAlarm(this, in, current);
            }
            case 6:
            {
                return _iceD_unregisterServer(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
